apiVersion: v1
kind: Service
metadata:
  name: model-service
  labels:
    app.kubernetes.io/name: model-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: model-service
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
